### ISSUE TITLE
Add newline separated json (JSONL) format

### ISSUE THREAD

**Issue by tracker1** [greggles/mcc-codes#25]
Would be nice to see a newline separated JSON format added... though the JSON size isn't too bad, it's still relatively big and newline-separated JSON is a bit easier for import.

Also, not sure if there are other updates as it looks like this repository is about 5 years from the last commit.

**Comment by greggles** [comment]
Yeah, times have changed a bit!

I agree with the idea of doing newline delimited json. I'll see what I can do.
